Garage2/Models/Receipt.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Garage2.Models {
    public class Receipt {
        [Display(Name = "Typ:")]
        public string Type  { get; set; }

        [Display(Name = "Regnr")]
        public string RegNr { get; set; }

        [Display(Name = "Ägare")]
        public string Member { get; set; }

        [Display(Name = "Parkeringstid")]
        public string ParkingTime { get; set; }

        [Display(Name = "Pris")]
        public string Price { get; set; }
    }
}

Garage2/Models/Statistics.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Garage2.Models {
    public class Statistics {
        [Display(Name = "Antal bilar:")]
        public int NrOfCars { get; set; }

        [Display(Name = "Antal bussar:")]
        public int NrOfBusses { get; set; }

        [Display(Name = "Antal båtar:")]
        public int NrOfBoats { get; set; }

        [Display(Name = "Antal flygplan:")]
        public int NrOfAirplanes { get; set; }

        [Display(Name = "Antal motorcyklar:")]
        public int NrOfMotorcycles { get; set; }

        [Display(Name = "Totalt antal hjul:")]
        public int NrOfWheels { get; set; }

        [Display(Name = "Pris för alla fordon:")]
        public int PriceAllVehicles { get; set; }
    }
}

Garage2/Controllers/Vehicles1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Garage2.DAL;
using Garage2.Models;

namespace Garage2.Controllers
{
    public class Vehicles1Controller : Controller
    {
        private VehicleDBContext db = new VehicleDBContext();

        private int NrOfSpots = 18;
        private int PricePerHour = 60;

        // GET: Vehicles1
        public ActionResult Index(string dropDownTypes, string searchString)
        {
            ViewBag.FreeSpots = FreeSpots();

            //var types = db.VehicleTypes.Where(v => true).Select(v=>v.Type);
            var types2 = db.VehicleTypes.Select(v => v.Type);

            //ViewBag.dropDownTypes = new SelectList(types);
            ViewBag.dropDownTypes = new SelectList(types2); 
            
            var vehicles = db.Vehicles.Include(v => v.Member).Include(v => v.VehicleType);

            if (!String.IsNullOrEmpty(searchString)) {
                vehicles = vehicles.Where(v => v.RegNr.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(dropDownTypes)) {
                vehicles = vehicles.Where(v => v.VehicleType.Type == dropDownTypes);
            }


            return View(vehicles.ToList());
        }

        // GET: Vehicles1
        public ActionResult DetailedView(string dropDownTypes, string searchString) {
            var vehicles = db.Vehicles.Include(v => v.Member).Include(v => v.VehicleType);

            ViewBag.FreeSpots = FreeSpots();

            var types = db.VehicleTypes.Where(v => true).Select(v => v.Type);

            ViewBag.dropDownTypes = new SelectList(types);

            if (!String.IsNullOrEmpty(searchString)) {
                vehicles = vehicles.Where(v => v.RegNr.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(dropDownTypes)) {
                vehicles = vehicles.Where(v => v.VehicleType.Type == dropDownTypes);
            }

            return View(vehicles.ToList());
        }

        public ActionResult Statistics() {
            Statistics statistics = new Statistics();
            var vehicles = db.Vehicles.Where(v => true);
            List<TimeSpan> duration = new List<TimeSpan>();

            // Count number of cars
            statistics.NrOfCars = vehicles.Where(v => v.VehicleType.Type == "Bil").Count();

            // Count number of busses
            statistics.NrOfBusses = vehicles.Where(v => v.VehicleType.Type == "Buss").Count();

            // Count number of boats
            statistics.NrOfBoats = vehicles.Where(v => v.VehicleType.Type == "Båt").Count();

            // Count number of airplanes
            statistics.NrOfAirplanes = vehicles.Where(v => v.VehicleType.Type == "Flygplan").Count();

            // Count number of motorcycles
            statistics.NrOfMotorcycles = vehicles.Where(v => v.VehicleType.Type == "Motorcykel").Count();

            // Count number of wheels in the garage
            statistics.NrOfWheels = vehicles.Select(v => v.Tyres).Sum();

            // Count total price for all vehicles in the garage
            foreach (var vehicle in vehicles) {
                duration.Add(DateTime.Now - vehicle.CheckInTime);
            }

            var totalTime = TimeSpan.Zero;
            foreach (TimeSpan currentValue in duration) {
                totalTime = totalTime + currentValue;
            }

            //int pricePerHour = 60;
            statistics.PriceAllVehicles = ((totalTime.Days * 24 + totalTime.Hours) * PricePerHour) + (totalTime.Minutes % PricePerHour);

            return View(statistics);
        }

        // GET: Receipt
        public ActionResult Receipt(Vehicle vehicle) {
            if (vehicle == null) {
                return HttpNotFound();
            }

            // Create receipt
            VehicleType vehicleType = db.VehicleTypes.Find(vehicle.VehicleTypeId);
            Member member = db.Members.Find(vehicle.MemberId);
            Receipt receipt = new Receipt();

            receipt.Type = vehicleType.Type;
            receipt.RegNr = vehicle.RegNr;
            receipt.Member = member.Name;
            receipt.ParkingTime = vehicle.ParkingTime;
            receipt.Price = vehicle.Price;

            return View(receipt);
        }

        // GET: Vehicles1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // GET: Vehicles1/Create
        public ActionResult Create()
        {
            ViewBag.MemberId = new SelectList(db.Members, "Id", "Name");
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Type");

            if (GarageIsFull()) {
                return RedirectToAction("FullGarage");
            } else {
                ViewBag.FreeSpots = FreeSpots();
                return View();
            }
        }

        // POST: Vehicles1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RegNr,Color,CheckInTime,Tyres,Brand,Model,SpotNr,MemberId,VehicleTypeId")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                vehicle.CheckInTime = DateTime.Now;
                vehicle.SpotNr = NextFreeSpot();
                db.Vehicles.Add(vehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MemberId = new SelectList(db.Members, "Id", "Name", vehicle.MemberId);
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Type", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // GET: Vehicles1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            ViewBag.MemberId = new SelectList(db.Members, "Id", "Name", vehicle.MemberId);
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Type", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // POST: Vehicles1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RegNr,Color,CheckInTime,Tyres,Brand,Model,SpotNr,MemberId,VehicleTypeId")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MemberId = new SelectList(db.Members, "Id", "Name", vehicle.MemberId);
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "Type", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // GET: Vehicles1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicle vehicle = db.Vehicles.Find(id);
            db.Vehicles.Remove(vehicle);
            db.SaveChanges();
            return RedirectToAction("Receipt", vehicle);
        }


        // GET: Vehicles/SearchVehicles
        public ActionResult SearchVehicles() {
            return View();
        }

        // Post: Vehicles/SearchVehicles
        [HttpPost]
        public ActionResult SearchVehicles(QueryObj queryObj) {
            return RedirectToAction("SearchResult", queryObj);
        }

        // GET: Vehicles
        public ActionResult SearchResult(QueryObj queryObj) {
            var query = db.Vehicles.Where(v => true);

            if (queryObj.VehicleType.Type != null) {
                query = query.Where(v => v.VehicleType.Type == queryObj.VehicleType.Type);
            }

            if (queryObj.RegNr != null) {
                query = query.Where(v => v.RegNr.ToLower().StartsWith(queryObj.RegNr.ToLower()));
            }

            if (queryObj.Color != null) {
                query = query.Where(v => v.Color.ToLower().StartsWith(queryObj.Color.ToLower()));
            }

            if (queryObj.Brand != null) {
                query = query.Where(v => v.Brand.ToLower().StartsWith(queryObj.Brand.ToLower()));
            }

            return View(query.OrderBy(v => v.RegNr).ToList()); // Always sort by regnr
        }

        private int NextFreeSpot() {
            var query = db.Vehicles.Where(v => v != null);
            for (int i = 1; i < this.NrOfSpots + 1; i++) {
                if (!query.Where(v => v.SpotNr == i).Any())
                    return i;
            }
            return 0; // if the garage is full
        }

Garage2/Views/Vehicles1/Create.cshtml
@model Garage2.Models.Vehicle

@{
    ViewBag.Title = "Create";
}

<h2 style="text-align:left; float:left;">Checka in fordon</h2>

<h3 style="text-align:right;">Lediga platser: @ViewBag.FreeSpots</h3>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.RegNr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegNr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegNr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleTypeId, "Typ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VehicleTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VehicleTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tyres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tyres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tyres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberId, "MemberId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MemberId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Checka in" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka till översiktsvy", "Index")
</div>

Garage2/Views/Vehicles1/Delete.cshtml
@model Garage2.Models.Vehicle

@{
    ViewBag.Title = "Delete";
}

<h2>Checka ut fordon</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Member.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Member.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VehicleType.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleType.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegNr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckInTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckInTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tyres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tyres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpotNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpotNr)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Checka ut" class="btn btn-default" />
            @*@Html.ActionLink("Visa alla fordon", "Index")*@
        </div>
    }
</div>

<br />

<div>
    @Html.ActionLink("Tillbaka till översiktsvy", "Index")
</div>

Garage2/Views/Vehicles1/DetailedView.cshtml
@model IEnumerable<Garage2.Models.Vehicle>

@{
    ViewBag.Title = "DetailedView";
}

<h2 style="text-align:left; float:left;">Detaljerad översiktsvy</h2>

<h3 style="text-align:right;">Lediga platser: @ViewBag.FreeSpots</h3>

@using (Html.BeginForm("Index", "Vehicles1", FormMethod.Get)) {
    <p>
        Typ: @Html.DropDownList("dropDownTypes", "All")
        Regnr: @Html.TextBox("SearchString")
        <span><input type="submit" value="Sök" /></span>
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VehicleType.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegNr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckInTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ParkingTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tyres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpotNr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Member.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VehicleType.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegNr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CheckInTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ParkingTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tyres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SpotNr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Member.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Ändra", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Checka ut", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Tillbaka till översiktsvy", "Index")
</div>

Garage2/Views/Vehicles1/Details.cshtml
@model Garage2.Models.Vehicle

@{
    ViewBag.Title = "Detaljer";
}

<h2>Detaljer</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.VehicleType.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VehicleType.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegNr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckInTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckInTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tyres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tyres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpotNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpotNr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Member.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Member.Name)
        </dd>


    </dl>
</div>

<div>
    @Html.ActionLink("Tillbaka till översiktsvy", "Index")
</div>

Garage2/Views/Vehicles1/Edit.cshtml
@model Garage2.Models.Vehicle

@{
    ViewBag.Title = "Edit";
}

<h2>Ändra fordonsinformation</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.RegNr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegNr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegNr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckInTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckInTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckInTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tyres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tyres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tyres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpotNr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpotNr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpotNr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberId, "MemberId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MemberId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleTypeId, "VehicleTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VehicleTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VehicleTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka till översiktsvy", "Index")
</div>

Garage2/Views/Vehicles1/Index.cshtml
@model IEnumerable<Garage2.Models.Vehicle>


@{
    ViewBag.Title = "Garage";

}

<h2 style="text-align:left; float:left;">Alla fordon</h2>

<h3 style="text-align:right;">Lediga platser: @ViewBag.FreeSpots</h3>

@using (Html.BeginForm("Index","Vehicles1",FormMethod.Get)) {
    <p>
        Typ: @Html.DropDownList("dropDownTypes", "All")
        Regnr: @Html.TextBox("SearchString") 
        <span><input type="submit" value="Sök" /></span>
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VehicleType.Type)
        </th>
        <th>
            <a href="?sort=regnr">
                @Html.DisplayNameFor(model => model.RegNr)
            </a>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ParkingTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpotNr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Member.Name)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleType.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegNr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParkingTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SpotNr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Member.Name)
            </td>

            <td>
                @Html.ActionLink("Detaljer", "Details", new { id = item.Id }) |
                @Html.ActionLink("Checka ut", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>